def generate_paths(left_images, folders, images_between):
    """
    Generates paths based on given parameters. Paths are generated by combining left[i] and left[i + images between + 1]
    from folder i.
    :param left_images: List of left images
    :param folders: List of used folders
    :param images_between: Number of images between
    :return: List of left images, right images, and gt images.
    """
    in1_all = []
    in2_all = []
    gt_all = []

    for n in range(len(images_between)):
        in1_paths = []
        in2_paths = []
        gt_paths = []

        ib = images_between[n]

        for i in range(len(left_images)):
            temp_gt = []
            survey_line = left_images[i]
            folder_str = "/{}/".format(folders[i])

            if folders[i] < 18:
                format_str = "{0:02d}.jpg"  # Determines the length of the image name (0.jpg vs 00.jpg etc.)
            else:
                format_str = "{}.jpg"

            in1 = folder_str + str(format_str.format(survey_line))
            in2 = folder_str + str(format_str.format(survey_line + ib + 1))

            for j in range(1, 1 + ib):
                path_str = folder_str + str(format_str.format(survey_line + j))
                temp_gt.append(path_str)

            in1_paths.append(in1)
            in2_paths.append(in2)
            gt_paths.append(temp_gt)

        in1_all.append(in1_paths)
        in2_all.append(in2_paths)
        gt_all.append(gt_paths)

    return in1_all, in2_all, gt_all